version: '3.8'

services:
  api:
    build: .
    container_name: heart-disease-api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./model:/app/model
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
